from .discriminators.identity_discriminator import IdentityDiscriminator
from .discriminators.sequence_discriminator import SequenceDiscriminatorCNN,SequenceDiscriminator
from .discriminators.sync_discriminator import SyncDiscriminator
from .discriminators.patch_disc import PatchDiscriminator